# Generated by Django 3.0.8 on 2020-07-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_title', models.CharField(max_length=50)),
                ('foto_rating', models.PositiveIntegerField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
