# Generated by Django 3.0.8 on 2020-07-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='media')),
                ('photo_rating', models.PositiveIntegerField(default=1400, null=True)),
                ('pub_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
